server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${application.spring.datasource.url}
    username: ${application.spring.datasource.username}
    password: ${application.spring.datasource.password}
    databaseAPI: ${application.spring.datasource.databaseAPI}


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  cloud:
    gcp:
      storage:
        credentials:
          location: ${application.spring.cloud.gcp.storage.credentials.location}
        project-id: ${application.spring.cloud.gcp.storage.project-id}
        bucket: ${application.spring.cloud.gcp.storage.bucket}
      geocodingAPI: ${application.spring.cloud.gcp.geocodingAPI}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


jwt:
  secret: ${application.jwt.secret}
  secret_refresh: ${application.jwt.secret_refresh}